[package]
name = "fit-bench"
version = "0.1.0"
authors = ["Richard Brodie <richard@radagast.nu>"]
edition = "2018"

[dev-dependencies]
fit = { path = "../fit" }
criterion = "^0.2"

[[bench]]
name = "read_file"
harness = false

